### PR TITLE
Work around Vagrant nonzero status for successful destroy

### PR DESCRIPTION
**Pull request by ararslan**
Recent versions of Vagrant exit with a nonzero status from `vagrant destroy` if a VM that Vagrant knows about isn't running (https://github.com/hashicorp/vagrant/issues/9137). So even if our script that runs Vagrant finished just fine, tearing down the VMs at the end will cause Julia to fail. Thus I've implemented a crude workaround that ignores the return status and instead parses the STDOUT and STDERR output of Vagrant.

cc @vchuravy

### CODE REVIEW

**Comment by tkelman** [comment]
How recent? I've never seen a failure here unless someone has gone behind vagrant's back and broken the VMs that should be under its control.

**Comment by vchuravy** [comment]
This was seen on nanosoldier3 with Vagrant 2.0.1

**Comment by tkelman** [comment]
Do you need a feature that is only in vagrant 2? If not, I think it's better to downgrade to 1.9 and avoid this mess.

**Comment by ararslan** [comment]
No longer needed. We're now on Vagrant 1.9 and we can update once the return code issue is fixed upstream.

**Pull request closed without merging**
