### PR TITLE
update link to package detail page

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by tkelman** [comment]
good call, where does this end up on the page?

**Comment by waldyrious** [comment]
IIUC it's only used in [pkgdetail.html](https://github.com/JuliaCI/PackageEvaluator.jl/blob/master/website/html/pkgdetail.html), in the "permalink" field right below the title -- e.g. http://pkg.julialang.org/detail/Example.

**Comment by tkelman** [comment]
Ah funny, "permalink" is a link to a different page. How useful is it for a page to link to itself, isn't copy-pasting the address bar equivalent? We could maybe just use a different label than "permalink" for this line. "Back to package list" or something?

**Comment by waldyrious** [comment]
Yes, I found it quite odd indeed. So you're suggesting changing the label and leaving the URL as-is, right? If so, I agree that it's more useful from the detail page, but I'd suggest changing the link to something like http://pkg.julialang.org/#Example instead. I'll update the PR.

(btw, the routing of `?pkg=` should probably be changed to redirect to the `/detail/` url, but that's probably best handled in a separate PR and by someone more acquainted with the site's internals).

**Comment by waldyrious** [comment]
I changed the permalink in the detail page to point back to the list page (with an anchor to the package's entry), and while I was at it, I added a "permalink" link to the listing page, where it actually makes sense.

**Pull request merged**
