### PR TITLE
Don't test several CUDAnative-related packages

### PR DESCRIPTION
**Pull request by maleadt**
All of these are covered by my CI though (by necessity).

### CODE REVIEW

**Comment by ararslan** [comment]
Is there some reason why this hasn't already been merged?

**Comment by tkelman** [comment]
LLVM shouldn't require a gpu

**Comment by ararslan** [comment]
Okay, so should the LLVM line be removed here?

**Comment by maleadt** [comment]
> LLVM shouldn't require a gpu

As mentioned in the comment `requires llvm-config`, currently unsatisfiable by binary Julia dists.
So I'd prefer to disable LLVM for now, and re-enable it when we have the CI support.

**Comment by tkelman** [comment]
In that case "fails" is an accurate representation.

**Comment by andreasnoack** [comment]
People should be free to opt out. In particular, if they have a good reason and are carefully testing their packages elsewhere.

**Comment by tkelman** [comment]
LLVM no longer needs to opt out, this is stale.

**Comment by maleadt** [comment]
That only works on 0.7 though, any way to restrict the testing?

**Comment by tkelman** [comment]
"only works on 0.7" is then, again, still, an accurate thing for pkgeval to say, given it's not running in a source build

**Comment by maleadt** [comment]
> "only works on 0.7" is then, again, still, an accurate thing for pkgeval to say

Sure it is, just trying to improve the SNR (if it's never going to pass, why bother reporting the failure).

**Pull request merged**
