### PR TITLE
Drop 0.4, add 0.7

### PR DESCRIPTION
**Pull request by ararslan**
The only part that I haven't done is update the plot code to show 0.7 since that will take fiddling with the axes and all of that. That seems less urgent than getting things working again and having 0.7 on there.

cc @aviks

### CODE REVIEW

**Comment by tkelman** [comment]
METADATA should be frozen for 0.4 first

**Comment by ararslan** [comment]
Okay. How do I do that?

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/6146

**Comment by ararslan** [comment]
Cool, thanks!

**Comment by ararslan** [comment]
For anyone else reading this: METADATA PR at https://github.com/JuliaLang/METADATA.jl/pull/11985

**Comment by ararslan** [comment]
I just got a final run with 0.4 through. 🎉

**Pull request merged**
