### PR TITLE
Install geographiclib for GeographicLibPy.jl

### PR DESCRIPTION
**Pull request by kshramt**

### CODE REVIEW

**Comment by IainNZ** [comment]
@kshramt you might want to try to use Conda.jl to install this package automatically rather than doing it this way - I know many of the Python-wrapping packages do this now, but I don't know exactly how it works.

**Comment by kshramt** [comment]
@IainNZ 
 Sorry, I was missing some previous discussions (<https://github.com/JuliaCI/PackageEvaluator.jl/pull/105>).
Although geographiclib is [not provided by Conda](https://docs.continuum.io/anaconda/pkg-docs) now, I will close this pull-request since Conda.jl seems to be a de facto standard to manage Python packages as you commented.

**Comment by tkelman** [comment]
Maybe look into the conda-forge channel as a way of getting geographiclib packaged?

**Comment by kshramt** [comment]
Thank you for the suggestion.
I will take a look at it.

**Pull request closed without merging**
