### PR TITLE
test on 0.6-dev instead of 0.3

### PR DESCRIPTION
**Pull request by tkelman**
will revert https://github.com/JuliaCI/PackageEvaluator.jl/commit/f65c6c9193f60514febdbd17f66904c4ce84eec1, that's just for testing purpose to avoid breaking the live website if this goes horribly wrong

I'm going to want to change the pulse a little to show test status changes on all of 0.4, 0.5, and 0.6-dev. I've been manually checking 0.3 changes from the diff which is getting old.

### CODE REVIEW

**Comment by IainNZ** [comment]
RIP 0.3, you fought the good fight

**Comment by tkelman** [comment]
now how do I render https://github.com/JuliaCI/pkg.julialang.org/tree/test06

**Comment by IainNZ** [comment]
`python -m SimpleHTTPServer`?

**Comment by tkelman** [comment]
that probably requires more fiddling than https://htmlpreview.github.io/

**Comment by tkelman** [comment]
Vagrant hung on last night's cronjob run, not sure why. Finished correctly, but ruby was stuck - after killing the ruby process everything went through and we're in business http://pkg.julialang.org/pulse.html. Hopefully the freeze won't happen again. I should probably create a summary file that just lists all the statuses in a simple text file, like I manually make for checking backports. Then could diff what broken on 0.6-dev since it branched relative to 0.5.

**Pull request merged**
